version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_historial
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: historias_clinicas
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped

  backend:
    build: .
    container_name: flask_backend
    ports:
      - "777:777"
    environment:
      - SECRET_KEY=medilogix140725
      - JWT_SECRET_KEY=medilogix140725
    depends_on:
      - mysql
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  dbdata:
